/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppComponent {}
  interface MyComponent {
    'changeLast': (s: string) => void;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface TestRain {}
}

declare global {


  interface HTMLAppComponentElement extends Components.AppComponent, HTMLStencilElement {}
  var HTMLAppComponentElement: {
    prototype: HTMLAppComponentElement;
    new (): HTMLAppComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTestRainElement extends Components.TestRain, HTMLStencilElement {}
  var HTMLTestRainElement: {
    prototype: HTMLTestRainElement;
    new (): HTMLTestRainElement;
  };
  interface HTMLElementTagNameMap {
    'app-component': HTMLAppComponentElement;
    'my-component': HTMLMyComponentElement;
    'test-rain': HTMLTestRainElement;
  }
}

declare namespace LocalJSX {
  interface AppComponent {}
  interface MyComponent {
    'changeLast'?: (s: string) => void;
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface TestRain {}

  interface IntrinsicElements {
    'app-component': AppComponent;
    'my-component': MyComponent;
    'test-rain': TestRain;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-component': LocalJSX.AppComponent & JSXBase.HTMLAttributes<HTMLAppComponentElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'test-rain': LocalJSX.TestRain & JSXBase.HTMLAttributes<HTMLTestRainElement>;
    }
  }
}


